apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-ms
  template:
    metadata:
      labels:
        app: ai-ms
    spec:
      containers:
      - name: ai-ms
        image: europe-west1-docker.pkg.dev/iot-microservices-gcp/iot-repo/ai-ms:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongo"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_DB
          value: "iot"
        resources:
          limits:
            cpu: "1.0"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-ms
  namespace: default
spec:
  selector:
    app: ai-ms
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
