# Build stage
FROM node:16-alpine AS build-step
WORKDIR /app
COPY iot-app/package*.json ./
RUN npm install
COPY iot-app/ .
RUN ./node_modules/.bin/ng build --prod

# Final stage
FROM nginx:1.17.8-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY default.conf /etc/nginx/conf.d/
COPY --from=build-step /app/dist/iot-app/ /usr/share/nginx/html
